spring.application.name=product

server.port=2425

#server.servlet.context-path=jk

spring.datasource.url=jdbc:postgresql://localhost:5432/jkdatabase
spring.datasource.username=postgres
spring.datasource.password=2425
spring.jpa.hibernate.ddl-auto=update
